# vim: ft=python expandtab
from subprocess import Popen, PIPE

Import('env')
env_gtk_engine_svg = env.Clone(PDB = 'libsvg.pdb')

env_gtk_engine_svg.Append(CPPPATH=['#'])

libgtk_engine_svg_SOURCES =Split("\
	svg-draw.c		\
	svg-render.c		\
	svg-rc-style.c")
env_gtk_engine_svg.ParseConfig('pkg-config atk --cflags --libs')

gtk_binary_version = Popen(['pkg-config', 'gtk+-2.0', '--variable=gtk_binary_version'], stdout=PIPE).communicate()[0].rstrip('\r\n')

rsvg_loader_dll = env_gtk_engine_svg.SharedLibrary('librsvg', libgtk_engine_svg_SOURCES + ['#librsvg-2.lib'])
env_gtk_engine_svg.AddPostAction(rsvg_loader_dll, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')
loader_install = env_gtk_engine_svg.Install('$PREFIX/lib/gtk-2.0/' + gtk_binary_version + '/engines', 'libsvg.dll')
if env_gtk_engine_svg['DEBUG'] == 1:
    Alias('install', env_gtk_engine_svg.Install('$PREFIX/pdb', env_gtk_engine_svg['PDB']))
 
